"""
scenarios/from_text.py
======================
Free-form natural-language scenario parser for Consensus Engine.

IMPORTANT — SCOPE NOTICE
-------------------------
Scenarios generated by this module are **unvalidated / exploratory**.
They are NOT covered by the N=30 statistical benchmarks documented in the
README (business_deal, roommate, trip_planning, strategic_negotiation).
Results obtained from free-form scenarios are illustrative and should NOT
be cited as evidence of the engine's negotiation performance.

Design model
------------
The user describes a negotiation situation in plain text. The LLM extracts:
  - Issues (name, range, what higher/lower means)
  - Stakeholders (name, role, utility weights, ideal values, reservation value)

Any party whose preferences are NOT explicitly provided by the user gets
LLM-invented ("llm_inferred") values. The ParseReport exposes this
provenance so the UI can label it — invented numbers are never presented
as user-provided data.
"""
from __future__ import annotations

import base64
import json
import logging
from dataclasses import dataclass, field, asdict
from typing import Literal

from pydantic import BaseModel, Field, model_validator

from src.llm.client import structured_completion
from src.models.utility import Issue, UtilityFunction, StakeholderProfile

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────────────
# Pydantic models used ONLY for LLM structured output
# ──────────────────────────────────────────────────────────────────────────────

MAX_ISSUES = 6   # >6 → reject (grid search / MC both become infeasible)
MC_THRESHOLD = 4  # >4 → switch to Monte Carlo approximation


class _LLMIssue(BaseModel):
    """One negotiation issue as extracted by the LLM."""
    name: str = Field(description="Snake_case identifier, e.g. 'rent_split'")
    min_value: float = Field(description="Minimum numeric value of this issue")
    max_value: float = Field(description="Maximum numeric value of this issue")
    description: str = Field(
        description="One sentence: what higher value means, what lower value means"
    )


class _LLMStakeholder(BaseModel):
    """One negotiating party as extracted/inferred by the LLM."""
    name: str = Field(description="Party identifier, e.g. 'Buyer', 'SupplierCo'")
    role: str = Field(description="Short role label, e.g. 'Buyer', 'Tenant'")
    persona: str = Field(description="1–2 sentence description of their negotiation stance")
    weights: dict[str, float] = Field(
        description="Utility weight per issue — will be renormalized to sum=1"
    )
    ideal_values: dict[str, float] = Field(
        description="Preferred value per issue within its [min, max] range"
    )
    reservation_value: float = Field(
        default=0.35,
        description="Minimum acceptable overall utility (0–1). Default 0.35 if unknown.",
    )
    source: Literal["user_specified", "llm_inferred"] = Field(
        description=(
            "user_specified = user explicitly described this party's preferences; "
            "llm_inferred = LLM invented plausible preferences for this party"
        )
    )

    @model_validator(mode="after")
    def renormalize_weights(self) -> "_LLMStakeholder":
        total = sum(self.weights.values())
        if total > 0 and abs(total - 1.0) > 0.01:
            factor = 1.0 / total
            self.weights = {k: round(v * factor, 6) for k, v in self.weights.items()}
        return self


class _LLMScenarioResponse(BaseModel):
    """Full structured output from the scenario-parsing LLM call."""
    issues: list[_LLMIssue] = Field(description="2–6 negotiation issues")
    stakeholders: list[_LLMStakeholder] = Field(description="2+ negotiating parties")
    warnings: list[str] = Field(
        default_factory=list,
        description=(
            "Anything the parser was unsure about — ambiguous parties, "
            "missing information, questionable ranges, etc."
        ),
    )


# ──────────────────────────────────────────────────────────────────────────────
# Public ParseReport dataclass
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class ParseReport:
    """
    Returned alongside the (profiles, issues) tuple.
    The API serialises this for the frontend confirmation step.
    Nothing runs until the user explicitly confirms this report.
    """
    # Parsed objects (same as the tuple elements)
    issues: list[dict] = field(default_factory=list)            # issues-meta dicts
    profiles: list[dict] = field(default_factory=list)          # StakeholderProfile.model_dump()

    # Provenance — which stakeholders had LLM-invented preferences
    stakeholder_sources: dict[str, Literal["user_specified", "llm_inferred"]] = field(
        default_factory=dict
    )

    # Human-readable notes surfaced in the UI confirmation screen
    field_notes: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    # Metadata for UI display
    issue_count: int = 0
    pareto_mode: Literal["exhaustive", "monte_carlo"] = "exhaustive"

    def to_dict(self) -> dict:
        return asdict(self)

    def to_token(self) -> str:
        """Encode as a base64 JSON token for round-tripping through the API."""
        payload = {
            "issues_meta": self.issues,
            "profiles": self.profiles,
        }
        raw = json.dumps(payload, separators=(",", ":"))
        return base64.b64encode(raw.encode()).decode()

    @staticmethod
    def decode_token(token: str) -> tuple[list[StakeholderProfile], list[dict]]:
        """Reconstruct (profiles, issues) from a round-trip token."""
        raw = base64.b64decode(token.encode()).decode()
        payload = json.loads(raw)
        profiles = [StakeholderProfile(**p) for p in payload["profiles"]]
        issues = payload["issues_meta"]
        return profiles, issues


# ──────────────────────────────────────────────────────────────────────────────
# Prompt builders
# ──────────────────────────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """You are a negotiation scenario parser for the Consensus Engine multi-agent system.

Your job is to read a natural-language description of a negotiation situation and extract:
1. A list of 2–6 distinct, quantifiable ISSUES (things to negotiate over, with numeric ranges).
2. A list of STAKEHOLDERS (negotiating parties) with utility weights and ideal values.

CRITICAL RULES:
- Issues must be quantifiable with clear numeric ranges (not binary yes/no).
- Weights per stakeholder must cover ALL issues you define (can be 0 but must be present).
- If the user did not describe a party's preferences, mark them as source="llm_inferred"
  and generate PLAUSIBLE preferences — do NOT fabricate them without marking them.
- If user described a party's preferences explicitly, mark them source="user_specified".
- reservation_value should be 0.25–0.55 for most parties (0.35 if completely unknown).
- ideal_values must fall within [min_value, max_value] for each issue.
- weights will be renormalized automatically, but try to make them sum ≈ 1.
- Add a warning for anything ambiguous or that required significant assumptions."""


def _build_user_message(text: str) -> str:
    return (
        f"Parse this negotiation description into a structured scenario:\n\n"
        f"---\n{text.strip()}\n---\n\n"
        f"Extract 2–6 issues and all negotiating parties. "
        f"Be conservative: if fewer issues clearly cover the situation, prefer fewer. "
        f"Mark any party whose preferences you had to invent as source='llm_inferred'."
    )


# ──────────────────────────────────────────────────────────────────────────────
# Main public function
# ──────────────────────────────────────────────────────────────────────────────

def generate_from_description(
    text: str,
    seed: int = 42,
) -> tuple[list[StakeholderProfile], list[dict], ParseReport]:
    """
    Parse a free-text negotiation description into engine-compatible objects.

    Parameters
    ----------
    text : str
        Natural-language description of the negotiation scenario.
    seed : int
        Not used for generation (LLM is non-deterministic) but stored in
        the report for reproducibility labelling.

    Returns
    -------
    profiles : list[StakeholderProfile]
        Drop-in replacement for the tuple element from any fixed scenario.
    issues_meta : list[dict]
        Drop-in replacement — each dict has {name, range: [min, max], description}.
    report : ParseReport
        Validation report. MUST be shown to the user for confirmation
        before calling run_negotiation(). Do not silently run on this output.

    Raises
    ------
    ValueError
        If the text describes more than 6 issues (computationally infeasible).
    """
    if not text or len(text.strip()) < 20:
        raise ValueError(
            "Description is too short. Please provide at least a sentence "
            "describing the parties and what they are negotiating over."
        )

    messages = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {"role": "user", "content": _build_user_message(text)},
    ]

    logger.info("Parsing free-form scenario (%d chars)", len(text))

    llm_response: _LLMScenarioResponse = structured_completion(
        messages=messages,
        response_model=_LLMScenarioResponse,
        temperature=0.2,  # lower temperature = more deterministic parsing
    )

    # ── Validate issue count ──────────────────────────────────────────────────
    n_issues = len(llm_response.issues)
    if n_issues > MAX_ISSUES:
        raise ValueError(
            f"The parser extracted {n_issues} issues from your description, but "
            f"Consensus Engine supports a maximum of {MAX_ISSUES} issues for "
            f"free-form scenarios. The Pareto-frontier search becomes computationally "
            f"infeasible beyond that. Please simplify your description by combining "
            f"related issues or removing less important ones, then try again."
        )
    if n_issues < 2:
        raise ValueError(
            "At least 2 negotiation issues are required. Please provide a more "
            "detailed description that includes multiple things the parties disagree on."
        )

    # ── Validate stakeholder count ────────────────────────────────────────────
    if len(llm_response.stakeholders) < 2:
        raise ValueError(
            "At least 2 negotiating parties are required. "
            "Please describe at least two parties with different interests."
        )

    # ── Build Issue objects ───────────────────────────────────────────────────
    issue_names = [i.name for i in llm_response.issues]
    issues: list[Issue] = []
    for llm_issue in llm_response.issues:
        if llm_issue.min_value >= llm_issue.max_value:
            # Swap silently and add a warning
            llm_response.warnings.append(
                f"Issue '{llm_issue.name}': min_value >= max_value — values were swapped."
            )
            llm_issue.min_value, llm_issue.max_value = llm_issue.max_value, llm_issue.min_value
        issues.append(Issue(
            name=llm_issue.name,
            min_value=llm_issue.min_value,
            max_value=llm_issue.max_value,
            description=llm_issue.description,
        ))

    issues_meta = [
        {"name": i.name, "range": [i.min_value, i.max_value], "description": i.description}
        for i in issues
    ]

    # ── Build StakeholderProfile objects ─────────────────────────────────────
    profiles: list[StakeholderProfile] = []
    stakeholder_sources: dict[str, str] = {}
    field_notes: list[str] = []

    for llm_sh in llm_response.stakeholders:
        # Ensure all issues covered in weights and ideal_values
        weights = dict(llm_sh.weights)
        ideal_values = dict(llm_sh.ideal_values)

        for iss in issues:
            if iss.name not in weights:
                weights[iss.name] = 1.0 / n_issues
                llm_response.warnings.append(
                    f"'{llm_sh.name}': missing weight for '{iss.name}' — set to uniform."
                )
            if iss.name not in ideal_values:
                mid = (iss.min_value + iss.max_value) / 2
                ideal_values[iss.name] = mid
                llm_response.warnings.append(
                    f"'{llm_sh.name}': missing ideal for '{iss.name}' — set to midpoint {mid}."
                )
            else:
                # Clamp to range
                ideal_values[iss.name] = max(
                    iss.min_value, min(iss.max_value, ideal_values[iss.name])
                )

        # Renormalize weights
        total = sum(weights.values())
        if total > 0:
            weights = {k: round(v / total, 6) for k, v in weights.items()}

        # Clamp reservation value
        rv = max(0.1, min(0.9, llm_sh.reservation_value))

        profile = StakeholderProfile(
            name=llm_sh.name,
            role=llm_sh.role,
            persona=llm_sh.persona,
            utility_function=UtilityFunction(
                weights=weights,
                ideal_values=ideal_values,
                issues=issues,
            ),
            reservation_value=rv,
        )
        profiles.append(profile)
        stakeholder_sources[llm_sh.name] = llm_sh.source

        if llm_sh.source == "llm_inferred":
            field_notes.append(
                f"⚠️  {llm_sh.name}'s preferences (weights, ideal values, "
                f"reservation value) were generated by the LLM — they are "
                f"plausible estimates, not user-provided data."
            )

    # ── Determine Pareto mode ─────────────────────────────────────────────────
    pareto_mode: Literal["exhaustive", "monte_carlo"] = (
        "monte_carlo" if n_issues > MC_THRESHOLD else "exhaustive"
    )
    if pareto_mode == "monte_carlo":
        field_notes.append(
            f"ℹ️  This scenario has {n_issues} issues. The Pareto-frontier "
            f"will be computed via Monte Carlo sampling (100,000 random points) "
            f"rather than exhaustive grid search. Results are marked 'approximate'."
        )

    # ── Build ParseReport ────────────────────────────────────────────────────
    report = ParseReport(
        issues=issues_meta,
        profiles=[p.model_dump() for p in profiles],
        stakeholder_sources=stakeholder_sources,
        field_notes=field_notes,
        warnings=llm_response.warnings,
        issue_count=n_issues,
        pareto_mode=pareto_mode,
    )

    logger.info(
        "Parsed scenario: %d issues, %d stakeholders, pareto_mode=%s, "
        "%d llm_inferred parties",
        n_issues,
        len(profiles),
        pareto_mode,
        sum(1 for s in stakeholder_sources.values() if s == "llm_inferred"),
    )

    return profiles, issues_meta, report
